blog/authors/urls.py
from django.urls import path
from django.views.generic import TemplateView

import authors.views as authors


app_name = 'authors'

urlpatterns = [
    path('', authors.index, name='index'),
    path('posts/', authors.PostsListView.as_view(), name='posts_list'),
    path('authors/<int:pk>/', authors.PostDetailView.as_view(), name='post_detail'),
    path('authors/', authors.AuthorsListView.as_view(), name='authors_list'),
    path('authors/posts/<int:name_id>/', authors.list_post_by_author, name='list_post_by_author'),
    path('authors/post/add/', authors.PostCreateView.as_view(), name='post_create'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.settings import DEBUG

urlpatterns = [
    path('', include('authors.urls', namespace='authors')),

    path('', include('myauth.urls', namespace='myauth')),

    path('admin/', admin.site.urls),
]

if DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

blog/myauth/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView
import myauth.views as myauth

app_name = 'myauth'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),

    path('user/create/', myauth.MyUserCreateView.as_view(),
         name='user_create'),

    path('logout/', LogoutView.as_view(),
         name='logout'),

    path('user/<int:pk>/', myauth.UserDetailView.as_view(),
         name='user_detail'),

    path('user/edit/<int:item_pk>/', myauth.UserUpdateView.as_view(),
         name='user_update'),

]

blog/authors/models.py
from django.db import models
from myauth.models import MyUser

# Create your models here.


# class Authors(models.Model):
#     name = models.CharField(max_length=64)
#     email = models.EmailField()
#     rating = models.IntegerField(default=0)
#
#     def __str__(self):
#         return f'{self.name}'
#
#     class Meta:
#         verbose_name = 'Имя автора'
#         verbose_name_plural = 'Имена авторов'
#         ordering = ['name']


class Post(models.Model):
    name = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=64)
    body = models.TextField()

    def __str__(self):
        return f'{self.name}  Title: {self.title}'

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ['name']


class Tag(models.Model):
    name = models.CharField(max_length=64)
    tag = models.ManyToManyField(Post)

    def __str__(self):
        return self.name

blog/myauth/models.py
from django.db import models

from django.contrib.auth.models import User, AbstractUser


class MyUser(AbstractUser):
    email = models.EmailField('email address', unique=True)
    d_birth = models.DateField(blank=True, null=True)
    bio = models.TextField(blank=True)
    avatar = models.ImageField(blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

blog/authors/forms.py
from django.forms import ModelForm
from authors.models import Post


class PostCreateViewForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field_obj in self.fields.items():
            field_obj.widget.attrs['class'] = 'form-control'

blog/myauth/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from myauth.models import MyUser


class MyUserCreateForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field_obj in self.fields.items():
            field_obj.help_text = ''
            field_obj.widget.attrs['class'] = 'form-control'
            # print(field_name, field_obj.help_text)


class MyUserUpdateViewForm(ModelForm):
    class Meta:
        model = MyUser
        fields = ('first_name', 'last_name', 'email', 'd_birth', 'bio',)
        labels = {'d_birth': 'Date birth'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field_obj in self.fields.items():
            field_obj.widget.attrs['class'] = 'form-control'
            print(field_name, field_obj.widget)

blog/authors/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.shortcuts import render
from django.urls import reverse, reverse_lazy

from authors.models import Post
from authors.forms import PostCreateViewForm

from myauth.models import MyUser

from django.views.generic import ListView, DetailView, CreateView


def index(request):
    return render(request, 'authors/index.html')


def list_post_by_author(request, name_id):
    posts = Post.objects.filter(name_id=name_id).select_related('name').all()
    context = {'posts': posts}
    return render(request, 'authors/post_list_author.html', context)


class PostsListView(ListView):
    model = Post
    paginate_by = 10

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.select_related('name').all()
        return qs


class PostDetailView(DetailView):
    model = Post


class AuthorsListView(ListView):
    model = MyUser
    template_name = 'authors/author_list.html'
    paginate_by = 5

    def get_queryset(self):
        qs = MyUser.objects.filter(post__isnull=False)\
            .values('first_name', 'last_name', 'id')\
            .annotate(total=Count('id')).order_by('last_name')
        return qs


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostCreateViewForm

    def form_valid(self, form):
        form.instance.name_id = self.request.user.id
        return super().form_valid(form)

    def get_success_url(self):
        name_id = self.object.name_id
        return reverse_lazy('authors:list_post_by_author', kwargs={'name_id': name_id})

blog/myauth/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import CreateView, DetailView, UpdateView, ListView

from myauth.forms import MyUserCreateForm, MyUserUpdateViewForm
from myauth.models import MyUser


class MyUserCreateView(CreateView):
    model = MyUser
    success_url = '/'
    form_class = MyUserCreateForm


class UserDetailView(DetailView):
    model = MyUser


class UserUpdateView(UpdateView):
    model = MyUser
    pk_url_kwarg = 'item_pk'
    form_class = MyUserUpdateViewForm

    def get_success_url(self):
        user_id = self.object.id
        return reverse_lazy('myauth:user_detail', kwargs={'pk': user_id})

blog/authors/templates/authors/author_list.html
{% extends 'base.html' %}

{% block title %}
        Authors
{% endblock %}
{% block body %}

<h1>Authors</h1>
<ul>
    <div class="col-md-8">
                <ul  class="list-group list-group-flush">
                    {% for item in object_list %}

                    <div class="list-group-item">
                         {{ item.first_name }} {{ item.last_name }} stories:
                        <a href="{% url 'authors:list_post_by_author' item.id %}"> {{ item.total }} </a>
                    </div>
                    {% endfor %}
                </ul>
    </div>

</div>
</ul>
<nav aria-label="...">
       <ul class="pagination pagination-sm">
        {% if page_obj.has_previous %}
           <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
           <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"> << </a></li>
        {% endif %}

           <li class="page-item active" aria-current="page">
               <span class="page-link">{{ page_obj.number }}</span>
           </li>

        {% if page_obj.has_next %}
           <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"> >> </a></li>
           <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
        {% endif %}
        </ul>
        </nav>

</ul>

{% endblock %}

blog/authors/templates/authors/index.html
{% extends 'base.html' %}

{% block title %}
    Blog

{% endblock %}
{% block body %}
<h1>Welcome!</h1>

{% endblock %}

blog/authors/templates/authors/post_detail.html
{% extends 'base.html' %}

{% block title %}
{{ object.title }}
{% endblock %}

{% block body %}
<h1>{{ object.title }}</h1>
  <div
          class='body'>{{ object.body|safe }}
  </div>



    <div>
        <a class="btn btn-primary my-2" href="{% url 'authors:posts_list' %}">Back</a>
    </div>

{% endblock %}

blog/authors/templates/authors/post_form.html
{% extends "base.html" %}
{% block title %}
 Add post
{% endblock %}

{% block body %}
<div class="bg-light p-5 rounded">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p}}
        <hr>
        <button class="btn btn-primary" type="submit">Save</button>
    </form>
</div>
{% endblock %}

blog/authors/templates/authors/post_list.html
{% extends 'base.html' %}

{% block title %}
Post List
{% endblock %}
{% block body %}
<h1>Posts</h1>
<ul>

    <div class="posts-list">
    <ul class="list-group list-group-flush">
        {% for item in post_list %}
            <li class="list-group-item">
                {{ item }}
                <a href="{% url 'authors:post_detail' item.id %}">Detail</a>
            </li>
        {% endfor %}
    </ul>


    </div>
       <nav aria-label="...">
       <ul class="pagination pagination-sm">
<!--           <li class="page-item active" aria-current="page">-->
<!--               <span class="page-link">{{ page_obj.number }}</span>-->
<!--           </li>-->
        {% if page_obj.has_previous %}
           <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
           <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
        {% endif %}

           <li class="page-item active" aria-current="page">
               <span class="page-link">{{ page_obj.number }}</span>
           </li>
<!--        <span class="current">-->
<!--            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.-->
<!--        </span>-->

        {% if page_obj.has_next %}
           <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
           <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
        {% endif %}
        </ul>
        </nav>

</ul>
{% endblock %}

blog/authors/templates/authors/post_list_author.html
{% extends 'base.html' %}

{% block title %}
{{ posts.name }}
{% endblock %}

{% block body %}
<ul>

    <div class="posts-list">
    <ul class="list-group list-group-flush">
        {% for item in posts %}
            <li class="list-group-item">
                {{ item }}
                <a href="{% url 'authors:post_detail' item.id %}">Detail</a>
            </li>
        {% endfor %}
    </ul>

    <div>
        <a class="btn btn-primary my-2" href="{% url 'authors:authors_list' %}">Back</a>
    </div>

{% endblock %}

blog/authors/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title> {% block title %}
                Base title
            {% endblock %}
    </title>
</head>
<header>
  <div class="container-fluid">
<div class="row">

    <div class="col-md-1"></div>
    <div class="col-md-4">
    <a class="btn btn-primary my-2" href="{% url 'authors:index' %}">Main</a>
    <a class="btn btn-primary my-2"href="{% url 'authors:authors_list' %}">Authors list</a>
    <a class="btn btn-primary my-2" href="{% url 'authors:posts_list' %}">Posts list</a>
    </div>


    {% if user.is_authenticated %}

    <div class="col-md-3">
       <a class="btn btn-primary my-2" href="{% url 'authors:post_create' %}">Write post</a>
    </div>
  <div class="col-md-2">
      <a class="btn btn-light my-2" href="{% url 'myauth:user_detail' user.id %}">Hello {{ user.username }}!</a>
      <a class="btn btn-light my-2" href="{% url 'myauth:logout' %}">Logout</a>
  </div>

    {% else %}

     <div class="col-md-3"></div>
  <div class="col-md-2">
      <a class="btn btn-light my-2" href="{% url 'myauth:login' %}">Login</a>
      <a class="btn btn-light my-2" href="{% url 'myauth:user_create' %}">Register</a>
  </div>

    {% endif %}

  </div>
</div>
</header>

<body>

    <div>
        <div class="container">
            <div class="row align-items-center">
            {% block body %}
            {% endblock %}
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

blog/myauth/templates/myauth/myuser_detail.html
{% extends 'base.html' %}

{% block title %}
Profile
{% endblock %}

{% block body %}
<h1>{{ object.first_name }} {{ object.last_name }}</h1>
  <div>
      <h4>Username: {{ object.username|safe }}</h4>
  </div>

  <div>
      <h4>Register: {{ object.date_joined|safe }}</h4>
  </div>



    <div>
        <a class="btn btn-primary my-2" href="{% url 'myauth:user_update' user.id %}">Edit</a>
    </div>

{% endblock %}

blog/myauth/templates/myauth/myuser_form.html
{% extends "base.html" %}
{% block title %}
 Login
{% endblock %}

{% block body %}
<div class="bg-light p-5 rounded">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p}}
        <hr>
        <button class="btn btn-primary" type="submit">Save</button>
    </form>
</div>
{% endblock %}